name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Clone Repo
      uses: actions/checkout@v1
    
    - name: Setup Visual Studio Command Prompt
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build
      run: |
        msbuild /restore /t:Build src/Microsoft.SqlServer.Types.sln /p:Configuration=Release
        
    - name: Tests
      run: |
        dotnet test src/Microsoft.SqlServer.Types.Tests/bin/Release/netcoreapp2.0/Microsoft.SqlServer.Types.Tests.dll -v normal
